### ISSUE TITLE
Error: No Living connections

### ISSUE THREAD

**Issue by cdupont** [Waziup/ELS-feeder#3]
When started with the platform, feeder complains with:
```
els-feeder_1      | info: index: "waziup"
els-feeder_1      | info: Creating/updating an index for waziup
els-feeder_1      | info: Listening on port  9000
els-feeder_1      | Elasticsearch ERROR: 2017-12-01T22:10:20Z
els-feeder_1      |   Error: Request error, retrying
els-feeder_1      |   HEAD http://elasticsearch:9200/waziup => connect ECONNREFUSED 172.19.0.4:9200
els-feeder_1      |       at Log.error (/opt/feeder/node_modules/elasticsearch/src/lib/log.js:225:56)
els-feeder_1      |       at checkRespForFailure (/opt/feeder/node_modules/elasticsearch/src/lib/transport.js:258:18)
els-feeder_1      |       at HttpConnector.<anonymous> (/opt/feeder/node_modules/elasticsearch/src/lib/connectors/http.js:157:7)
els-feeder_1      |       at ClientRequest.bound (/opt/feeder/node_modules/lodash/dist/lodash.js:729:21)
els-feeder_1      |       at emitOne (events.js:96:13)
els-feeder_1      |       at ClientRequest.emit (events.js:191:7)
els-feeder_1      |       at Socket.socketErrorListener (_http_client.js:358:9)
els-feeder_1      |       at emitOne (events.js:96:13)
els-feeder_1      |       at Socket.emit (events.js:191:7)
els-feeder_1      |       at emitErrorNT (net.js:1279:8)
els-feeder_1      |       at _combinedTickCallback (internal/process/next_tick.js:80:11)
els-feeder_1      |       at process._tickCallback (internal/process/next_tick.js:104:9)
els-feeder_1      | 
els-feeder_1      | Elasticsearch WARNING: 2017-12-01T22:10:20Z
els-feeder_1      |   Unable to revive connection: http://elasticsearch:9200/
els-feeder_1      | 
els-feeder_1      | Elasticsearch WARNING: 2017-12-01T22:10:20Z
els-feeder_1      |   No living connections
els-feeder_1      | 
els-feeder_1      | error: ERROR in checking index Error: No Living connections
els-feeder_1      |     at sendReqWithConnection (/opt/feeder/node_modules/elasticsearch/src/lib/transport.js:225:15)
els-feeder_1      |     at next (/opt/feeder/node_modules/elasticsearch/src/lib/connection_pool.js:213:7)
els-feeder_1      |     at _combinedTickCallback (internal/process/next_tick.js:73:7)
els-feeder_1      |     at process._tickCallback (internal/process/next_tick.js:104:9)
els-feeder_1      | info: Creating an index for  waziup
els-feeder_1      | Elasticsearch WARNING: 2017-12-01T22:10:20Z
els-feeder_1      |   Unable to revive connection: http://elasticsearch:9200/
els-feeder_1      | 
els-feeder_1      | Elasticsearch WARNING: 2017-12-01T22:10:20Z
els-feeder_1      |   No living connections
els-feeder_1      | 
els-feeder_1      | error: ERROR in creating index Error: No Living connections
els-feeder_1      |     at sendReqWithConnection (/opt/feeder/node_modules/elasticsearch/src/lib/transport.js:225:15)
els-feeder_1      |     at next (/opt/feeder/node_modules/elasticsearch/src/lib/connection_pool.js:213:7)
els-feeder_1      |     at _combinedTickCallback (internal/process/next_tick.js:73:7)
els-feeder_1      |     at process._tickCallback (internal/process/next_tick.js:104:9)
```

It's probably due to the fact that elasticsearch is not started yet.
In a docker-compose environment, it's not possible to guaranty that one component should complete starting before another...
So feeder should probably wait in a loop that elasticsearch and also orion are responding.

**Comment by cdupont** [comment]
@malishahi this should be fixed?
